#!/bin/bash

############################################################
#Obligation d'être administrateur pour lancé cette commande#
############################################################

if [ "$UID" -ne "0" ]
then
   echo "Avez-vous les privilèges du superutilisateur ?"
   exit 1
fi

if [ $# = 0 ]; then
    read -p "Quelle configuration souhaitez-vous désactiver ? " fileName
    for i in `echo ${fileName} | tr " " " "`; do
        set ${fileName}
    done
fi

for fileName in $@; do
    if [ ! -h "/etc/nginx/sites-enabled/$fileName" ]; then
        echo -E "La configuration : \"$fileName\" n'est pas active"
        continue
    else
        `rm /etc/nginx/sites-enabled/${fileName}`
        sed -i "/127.0.0.1\t$fileName.dev/d" /etc/hosts
        echo -E "La configuration : \"$fileName\" a été désactivé"
    fi
done

fi
