#!/bin/bash

############################################################
#Obligation d'être administrateur pour lancé cette commande#
############################################################

if [ "$UID" -ne "0" ]
then
   echo "Avez-vous les privilèges du superutilisateur ?"
   exit 1
fi

`nginx -t >/dev/null 2>&1`
if [ $? = 0 ];then
    echo -E "ERREUR -> Un des fichiers de configuration présente une erreur. Activation des configurations impossible"
    exit 1
fi

if [ $# = 0 ]; then
    read -p "Quelle configuration souhaitez-vous activer ? " fileName
    for i in `echo ${fileName} | tr " " " "`; do
        set ${fileName}
    done
fi

for fileName in $@; do
    if [ ! -f "/etc/nginx/sites-available/$fileName" ]; then
        echo -E "ERREUR -> le fichier de configuration \"$fileName\" n'existe pas"
       continue
    elif [ -h "/etc/nginx/sites-enabled/$fileName" ]; then
        echo -E "La configuration : \"$fileName\" est déjà active"
        continue
    else
       `ln -s /etc/nginx/sites-available/${fileName} /etc/nginx/sites-enabled/${fileName}`
        sed -i "1i127.0.0.1\t$fileName.dev" /etc/hosts
        echo -E "La configuration : \"$fileName\" est activé"
    fi
done
